DROP TABLE IF EXISTS "categories";
CREATE TABLE "categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "label" varchar(255), "created_at" datetime, "updated_at" datetime);
INSERT INTO "categories" VALUES(1,'Habitação','','');
INSERT INTO "categories" VALUES(2,'Automóvel','','');
INSERT INTO "categories" VALUES(3,'Saúde','','');
INSERT INTO "categories" VALUES(4,'Transporte','','');
INSERT INTO "categories" VALUES(5,'Despesas Pessoais','','');
INSERT INTO "categories" VALUES(6,'Lazer','','');
INSERT INTO "categories" VALUES(8,'Banco','','');
DROP TABLE IF EXISTS "companies";
CREATE TABLE "companies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255));
INSERT INTO "companies" VALUES(1,'GVT');
INSERT INTO "companies" VALUES(2,'AESul');
INSERT INTO "companies" VALUES(3,'Renner');
DROP TABLE IF EXISTS "incomes";
CREATE TABLE "incomes" ("id" INTEGER PRIMARY KEY  NOT NULL ,"description" varchar(255),"date" date,"value" integer,"company_id" integer,"created_at" datetime,"updated_at" datetime);
INSERT INTO "incomes" VALUES(1,'Salario Leonardo',NULL,1000,NULL,'2010-02-27 05:47:03','2010-02-27 05:47:03');
DROP TABLE IF EXISTS "outcomes";
CREATE TABLE "outcomes" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "data_vencimento" date, "data_pagamento" date, "description" varchar(255), "value" integer, "subcategory_id" integer, "company_id" integer, "created_at" datetime, "updated_at" datetime);
INSERT INTO "outcomes" VALUES(8,'2010-11-02',NULL,'teste',123,12,1,'2010-02-27 15:20:16','2010-02-27 16:04:30');
INSERT INTO "outcomes" VALUES(9,'2009-11-12',NULL,'teste1',123,16,3,'2010-02-27 15:43:58','2010-02-27 15:43:58');
DROP TABLE IF EXISTS "schema_migrations";
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
INSERT INTO "schema_migrations" VALUES('20100226190553');
INSERT INTO "schema_migrations" VALUES('20100226192521');
INSERT INTO "schema_migrations" VALUES('20100226193544');
INSERT INTO "schema_migrations" VALUES('20100226193705');
INSERT INTO "schema_migrations" VALUES('20100227023202');
DROP TABLE IF EXISTS "sqlite_sequence";
CREATE TABLE sqlite_sequence(name,seq);
INSERT INTO "sqlite_sequence" VALUES('outcomes',9);
INSERT INTO "sqlite_sequence" VALUES('categories',8);
INSERT INTO "sqlite_sequence" VALUES('subcategories',42);
INSERT INTO "sqlite_sequence" VALUES('companies',3);
DROP TABLE IF EXISTS "subcategories";
CREATE TABLE "subcategories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "category_id" integer, "label" varchar(255), "created_at" datetime, "updated_at" datetime);
INSERT INTO "subcategories" VALUES(1,1,'Aluguel/Prestação','','');
INSERT INTO "subcategories" VALUES(2,1,'Condomínio','','');
INSERT INTO "subcategories" VALUES(3,1,'IPTU','','');
INSERT INTO "subcategories" VALUES(4,1,'Luz','','');
INSERT INTO "subcategories" VALUES(5,1,'Telefones','','');
INSERT INTO "subcategories" VALUES(6,1,'Supermercado','','');
INSERT INTO "subcategories" VALUES(7,1,'Empregada','','');
INSERT INTO "subcategories" VALUES(8,1,'Reformas/Consertos','','');
INSERT INTO "subcategories" VALUES(9,1,'Outros','','');
INSERT INTO "subcategories" VALUES(10,1,'Gás','','');
INSERT INTO "subcategories" VALUES(11,3,'Plano de Saúde','','');
INSERT INTO "subcategories" VALUES(12,3,'Médico','','');
INSERT INTO "subcategories" VALUES(13,3,'Dentista','','');
INSERT INTO "subcategories" VALUES(14,3,'Medicamentos','','');
INSERT INTO "subcategories" VALUES(15,3,'Outros','','');
INSERT INTO "subcategories" VALUES(16,2,'Prestação','','');
INSERT INTO "subcategories" VALUES(17,2,'Seguro','','');
INSERT INTO "subcategories" VALUES(18,2,'Combustível','','');
INSERT INTO "subcategories" VALUES(19,2,'Lavagens','','');
INSERT INTO "subcategories" VALUES(20,2,'IPVA','','');
INSERT INTO "subcategories" VALUES(21,2,'Mecânico','','');
INSERT INTO "subcategories" VALUES(22,2,'Multas','','');
INSERT INTO "subcategories" VALUES(23,2,'Outros','','');
INSERT INTO "subcategories" VALUES(24,5,'Higiene Pessoal','','');
INSERT INTO "subcategories" VALUES(25,5,'Cosméticos','','');
INSERT INTO "subcategories" VALUES(26,5,'Cabeleireiro','','');
INSERT INTO "subcategories" VALUES(27,5,'Vestuário','','');
INSERT INTO "subcategories" VALUES(28,5,'Lavanderia','','');
INSERT INTO "subcategories" VALUES(29,5,'Academia','','');
INSERT INTO "subcategories" VALUES(30,5,'Cursos','','');
INSERT INTO "subcategories" VALUES(31,5,'Outros','','');
INSERT INTO "subcategories" VALUES(32,6,'Restaurantes','','');
INSERT INTO "subcategories" VALUES(33,6,'Bares/Boates','','');
INSERT INTO "subcategories" VALUES(34,6,'Livraria/Jornal','','');
INSERT INTO "subcategories" VALUES(35,6,'Passagens','','');
INSERT INTO "subcategories" VALUES(36,6,'Hotéis','','');
INSERT INTO "subcategories" VALUES(37,6,'Passeios','','');
INSERT INTO "subcategories" VALUES(38,6,'Outros','','');
INSERT INTO "subcategories" VALUES(39,8,'Empréstimos','','');
INSERT INTO "subcategories" VALUES(40,8,'CPMF','','');
INSERT INTO "subcategories" VALUES(41,8,'Juros','','');
INSERT INTO "subcategories" VALUES(42,8,'Outros','','');
